# Generated by Django 5.0.6 on 2024-06-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victorine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
    ]
