# Generated by Django 5.0.6 on 2024-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victorine', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_ready_to_publish',
            field=models.BooleanField(default=False),
        ),
    ]
