# Generated by Django 5.0.3 on 2024-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='country_manuf',
            field=models.CharField(default='earth', max_length=50),
        ),
    ]
