# Generated by Django 5.0.3 on 2024-04-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name'], 'verbose_name_plural': 'products'},
        ),
    ]
