# Generated by Django 5.0.3 on 2024-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciept',
            field=models.FileField(null=True, upload_to='orders/reciepts/'),
        ),
    ]
